environment: development
name: ffc-pay-processing
namespace: ffc-pay
workstream: ffc-pay
image: ffc-pay-processing

labels:
  component: service

appInsights:
  key:

containerConfigMap:
  name: ffc-pay-processing-config-map

containerSecret:
  name: ffc-pay-processing-container-secret
  type: Opaque

service:
  port: 80
  type: ClusterIP

deployment:
  restartPolicy: Always
  priorityClassName: default
  replicas: 1
  minReplicas: 1
  maxReplicas: 4
  cpuThreshold: 80
  memoryThreshold: 80
  minReadySeconds: 0

container:
  imagePullPolicy: IfNotPresent
  requestMemory: 180Mi
  requestCpu: 100m
  limitMemory: 280Mi
  limitCpu: 300m
  port: 3008
  messageQueueHost: namespace.servicebus.windows.net
  processingTopicAddress: ffc-pay-processing
  processingSubscriptionAddress: ffc-pay-processing
  acknowledgementTopicAddress: ffc-pay-acknowledgement
  acknowledgementSubscriptionAddress: ffc-pay-processing
  returnTopicAddress: ffc-pay-return
  returnSubscriptionAddress: ffc-pay-processing
  paymentSubmitTopicAddress: ffc-pay-submit
  debtTopicAddress: ffc-pay-debt-data
  debtDataTopicAddress: ffc-pay-debt-data-response
  debtDataSubscriptionAddress: ffc-pay-processing
  qcTopicAddress: ffc-pay-quality-check
  qcSubscriptionAddress: ffc-pay-processing
  autoHoldTopUp: false
  autoHoldRecovery: false

postgresService:
  postgresDb: ffc_pay_processing
  # postgresExternalName is the external host name to which PostgreSQL
  # requests should be forwarded. If empty, PostgreSQL is assumed to be
  # within the cluster and accessible via postgresHost
  postgresExternalName:
  postgresHost: ffc-pay-processing-postgres
  postgresPort: 5432
  postgresSchema: public
  postgresUser: postgres

readinessProbe:
  path: /healthy
  port: 3008
  initialDelaySeconds: 60
  periodSeconds: 120
  failureThreshold: 5
  timeoutSeconds: 30

livenessProbe:
  path: /healthz
  port: 3008
  initialDelaySeconds: 70
  periodSeconds: 120
  failureThreshold: 5
  timeoutSeconds: 30

aadPodIdentity: true

azureIdentity:
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID
